using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace PokeOneWeb.Data.Entities
{
    /// <summary>
    /// Base class for the Location Interaction inheritance tree. A LocationInteraction models
    /// a feature of an ingame <see cref="Entities.Location"/> which a Player can interact with.
    /// The subclasses specify the kind of interaction and additional information associated with it.
    /// 
    /// When translating the inheritance tree to the database, all subclasses of <see cref="LocationInteraction"/>
    /// get merged with the LocationInteraction entity, separated by a distinction column specifying the original
    /// Entity type. That column is automatically generated by Entity Framework Core.
    /// 
    /// In order to ensure conflicting column names always explictly specify names for any additonal columns
    /// introduced in the subclass and prefix the column name with the entity / class name.
    /// </summary>
    public abstract class LocationInteraction
    {
        public int Id { get; set; }

        /// <summary>
        /// A textual description of where in the Location the interaction is placed.
        /// </summary>
        public string PlacementDescription { get; set; }

        /// <summary>
        /// The ingame X-coordinate of the location. For interactions that are larger than one tile choose the middlemost coordinate.
        /// </summary>
        public int X { get; set; }

        /// <summary>
        /// The ingame Y-coordinate of the location. For interactions that are larger than one tile choose the middlemost coordinate.
        /// </summary>
        public int Y { get; set; }

        /// <summary>
        /// Any optional notes on this interaction.
        /// </summary>
        public string Notes { get; set; }

        /// <summary>
        /// The Location this interaction is placed in.
        /// </summary>
        [ForeignKey("LocationId")]
        public Location Location { get; set; }

        /// <summary>
        /// Foreign key for the Location.
        /// </summary>
        public int LocationId { get; set; }
    }
}
